# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Escuela')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('paterno', models.CharField(max_length=20)),
                ('materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Grupo')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.TipoPersona'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Persona'),
        ),
    ]
