# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogos', '0002_auto_20170501_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_persona',
        ),
        migrations.DeleteModel(
            name='TipoPersona',
        ),
    ]
