# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalogos', '0003_auto_20170501_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=250)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalogos.Alumno')),
            ],
        ),
    ]
