# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='observacion',
            field=models.TextField(),
        ),
    ]
